name: Java CI with Maven for Windows executable build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: 20.2.0.java11
      - name: Make staging directory
        run: mkdir staging
      - name: Build as Windows application with Gluon
        run: mvn clean client:build & mvn client:package
        env:
          GRAALVM_HOME: /opt/hostedtoolcache/GraalVM/20.2.0-java11/x64
      - name: Copy native client to staging
        run: cp -r target/client/* staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging