# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Change GraalVM script permissions
      run: chmod +x ./.github/scripts/setup-ubuntu-graalvm.sh
#    - name: Setup GraalVM environment
#      run: .github/scripts/setup-ubuntu-graalvm.sh
#      shell: bash
    - name: GRAALVM_HOME set
      run: export GRAALVM_HOME=~/graalvm
      shell: bash
    - name: GRAALVM_HOME test
      run: echo "GRAALVM_HOME=$GRAALVM_HOME"
      shell: bash
    - name: Change libraries script permissions
      run: chmod +x ./.github/scripts/setup-ubuntu-libraries.sh
    - name: Setup libraries
      run: ./.github/scripts/setup-ubuntu-libraries.sh
      shell: bash
    - name: Make staging directory
      run: mkdir staging
    - name: Build JAR with Maven
      run: mvn -B package --file pom.xml
    - name: Copy JAR to staging
      run: cp target/*.jar staging
    - name: Build as native application with Gluon
      run: mvn clean client:build
    - name: Copy native client to staging
      run: cp -r target/client/* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
