name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: 20.2.0.java11
    - name: Make staging directory
      run: mkdir staging
    - name: Gluon License
      uses: gluonhq/gluon-build-license@v1
      with:
        gluon-license: ${{ secrets.GLUON_LICENSE }}
    - name: Gluon Build
      run: mvn -Pdesktop client:build client:package
      env:
        GRAALVM_HOME: ${{ env.JAVA_HOME }}
    - name: Copy native client to staging
      run: cp -r target/client/x86_64-darwin/Resistor* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

