# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Setup GraalVM environment
      run: ./.github/scripts/setup-windows-graalvm.sh
      shell: bash
    - name: Make staging directory
      run: mkdir staging
    - name: Build JAR with Maven
      run: mvn -B package --file pom.xml
    - name: Copy JAR to staging
      run: cp target/*.jar staging
    - name: Build as native application with Gluon
      run: mvn clean client:build
    - name: Copy native client to staging
      run: cp target/client/* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
