# Inspired by:
# https://github.com/Apple-Actions/Example-iOS/blob/master/.github/workflows/test.yml
# https://docs.gluonhq.com/client/0.1.33/#_ios

name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: 20.2.0.java11
    - name: Make staging directory
      run: mkdir staging
    - name: Build JAR with Maven
      run: mvn -B package
    - name: Gluon Build
      uses: gluonhq/gluon-build@v1
      with:
        gluon-license: ${{ secrets.GLUON_LICENSE }}
        target: 'macos'
#    - name: Build and package as MacOS application with Gluon
#      run: mvn client:build client:package
#      env:
#        GRAALVM_HOME: /System/Volumes/Data/Users/runner/hostedtoolcache/GraalVM/20.2.0-java11/x64/
    - name: Copy native client to staging
      run: cp -r target/client/x86_64-darwin/Resistor* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

