# https://github.com/marketplace/actions/setup-msbuild
# https://github.com/microsoft/setup-msbuild
# https://docs.gluonhq.com/#_windows

name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 20.2.0.java11
      - name: Make staging directory
        run: mkdir staging
      - name: Gluon Build
        uses: gluonhq/gluon-build@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}
          target: 'windows'
#      - name: Build and package as Windows application with Gluon
#        run: mvn client:build client:package
#        env:
#          GRAALVM_HOME: C:\hostedtoolcache\windows\GraalVM\20.2.0-java11\x64
      - name: Copy native client to staging
        run: cp -r target/client/x86_64-windows/*.exe staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
