# Inspired by:
# https://github.com/Apple-Actions/Example-iOS/blob/master/.github/workflows/test.yml
# https://docs.gluonhq.com/client/0.1.33/#_ios

name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: 20.2.0.java11
    - name: Make staging directory
      run: mkdir staging
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: be.webtechie.ResistorCalculatorApp
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - name: Build JAR with Maven
      run: mvn -B package
    - name: Copy JAR to staging
      run: cp target/*.jar staging
    - name: Build and package as iOS application with Gluon
      run: mvn -Pios client:build client:package
      env:
        GRAALVM_HOME: /System/Volumes/Data/Users/runner/hostedtoolcache/GraalVM/20.2.0-java11/x64/
        IOS_SIGNING_IDENTITY: ${{ secrets.IOS_SIGNING_IDENTITY }}
        IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
    - name: Copy native client to staging
      run: cp -r target/client/* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: target/client/arm64-ios/Resistor\ Calculator.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
