# https://github.com/marketplace/actions/setup-msbuild

name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: 20.2.0.java11
      - name: find cl.exe
        run: dir /s/b /A:D "D:*cl.exe*"
      - name: Make staging directory
        run: mkdir staging
      - name: Build JAR with Maven
        run: mvn -B package
      - name: Copy JAR to staging
        run: cp target/*.jar staging
      - name: Build and package as Windows application with Gluon
        run: mvn client:build client:package
        env:
          GRAALVM_HOME: C:\hostedtoolcache\windows\GraalVM\20.2.0-java11\x64
      - name: Copy native client to staging
        run: cp -r target/client/* staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
