# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Inspired by:
# https://github.com/Srijan-Sengupta/Purulia-Pollution-Check/blob/f0f7a44f9a5e1251242aace866c0372f859eafbc/.github/workflows/android.yml
# https://docs.gluonhq.com/client/0.1.33/#_android_development

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: 20.2.0.java11
    - name: Install libraries
      run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
    - name: Make staging directory
      run: mkdir staging
    - name: Build JAR with Maven
      run: mvn -B package --file pom.xml
    - name: Copy JAR to staging
      run: cp target/*.jar staging
    - name: Build as Linux application with Gluon
      run: mvn clean client:build & mvn client:package
      env:
        GRAALVM_HOME: /opt/hostedtoolcache/GraalVM/20.2.0-java11/x64
    - name: Build as Android application with Gluon
      run: mvn -Pandroid client:build & mvn -Pandroid client:package
      env:
        GRAALVM_HOME: /opt/hostedtoolcache/GraalVM/20.2.0-java11/x64
    - name: Copy native clients to staging
      run: cp -r target/client/* staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
